export enum emebetJobTypes {
  nanny = "Nanny",
  maid = "Maid",
  femaleTutor = "Tutor",
  privateNurse = "Private Nurse",
  sales = "Sales",
  informationTechnology = "Information Technology",
  customerService = "Customer service",
  accountingandFinance = "Accounting and Finance",
  salesandMarketing = "Sales and Marketing",
  secretarialandClerical = "Secretarial and Clerical",
  hotelandTourism = "Hotel and Tourism",
  humanResource = "Human resource",
  logistics = "Logistics",
  education = "Education",
  healthCare = "Health Care",
  engineering = "Engineering",
  economics = "Economics",
  management = "Management",
  other = "Other",
}
